- id: doi:10.1002/celc.202300659
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/88b7562a-9483-4af6-b557-a682d2f90c9f/celc202300659-toc-0001-m.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/celc.202300659.pdf

- id: doi:10.1016/j.coelec.2023.101352
  image: https://ars.els-cdn.com/content/image/1-s2.0-S245191032300145X-gr1.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/j.coelec.2023.101352.pdf

- id: doi:10.1021/acs.jpcc.3c01727
  image: https://pubs.acs.org/cms/10.1021/acs.jpcc.3c01727/asset/images/large/jp3c01727_0010.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.3c01727.pdf

- id: doi:10.1021/acs.jpcc.3c00207 
  image: https://pubs.acs.org/cms/10.1021/acs.jpcc.3c00207/asset/images/large/jp3c00207_0008.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.3c00207.pdf

- id: doi:10.1002/cctc.202300055
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/70be5d84-06c5-4e8f-b41d-277c2940d40c/cctc202300055-toc-0001-m.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/cctc.202300055.pdf

- id: doi:10.1038/s41467-023-36318-1
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-023-36318-1/MediaObjects/41467_2023_36318_Fig2_HTML.png?as=webp
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/s41467-023-36318-1.pdf

- id: doi:10.1021/acs.jpcc.2c08222
  image: https://pubs.acs.org/cms/10.1021/acs.jpcc.2c08222/asset/images/large/jp2c08222_0008.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.2c08222.pdf

- id: doi:10.1016/j.electacta.2022.141443
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0013468622016000-ga1_lrg.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/j.electacta.2022.141443.pdf

- id: doi:10.1016/j.nanoms.2022.09.003
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2589965122000514-gr1_lrg.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/j.nanoms.2022.09.003.pdf

- id: doi:10.1002/cctc.202200932
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/d7e95c7b-5632-40ab-b84d-8da6aea46ece/cctc202200932-toc-0001-m.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/cctc.202200932.pdf

- id: doi:10.1021/acs.jpcc.2c03117
  image: https://pubs.acs.org/cms/10.1021/acs.jpcc.2c03117/asset/images/medium/jp2c03117_0006.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.2c03117.pdf

- id: doi:10.1021/jacsau.2c00143
  image: https://pubs.acs.org/cms/10.1021/jacsau.2c00143/asset/images/medium/au2c00143_0010.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/jacsau.2c00143.pdf

- id: doi:10.1021/acs.jpclett.1c04187
  image: https://pubs.acs.org/cms/10.1021/acs.jpclett.1c04187/asset/images/medium/jz1c04187_0006.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpclett.1c04187.pdf

- id: doi:10.1021/acscatal.1c02074
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/accacs/2021/accacs.2021.11.issue-15/acscatal.1c02074/20210802/images/large/cs1c02074_0012.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acscatal.1c02074.pdf
 
- id: doi:10.1002/anie.202100337
  image: https://onlinelibrary.wiley.com/cms/asset/ab50c403-ca8c-499b-85b2-48e6d924513b/anie202100337-toc-0001-m.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/anie.202100337.pdf
 
- id: doi:10.1021/acsenergylett.1c00234
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aelccp/2021/aelccp.2021.6.issue-3/acsenergylett.1c00234/20210305/images/medium/nz1c00234_0004.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acsenergylett.1c00234.pdf
 
- id: doi:10.1021/acsanm.0c02768
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aanmf6/2021/aanmf6.2021.4.issue-1/acsanm.0c02768/20210115/images/large/an0c02768_0008.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acsanm.0c02768.pdf
 
- id: doi:10.1021/acsaem.0c00972
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aaemcq/2020/aaemcq.2020.3.issue-8/acsaem.0c00972/20200817/images/large/ae0c00972_0006.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acsaem.0c00972.pdf
 
- id: doi:10.1103/PhysRevApplied.14.014068
  image: https://journals.aps.org/prapplied/article/10.1103/PhysRevApplied.14.014068/figures/2/medium
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/PhysRevApplied.14.014068.pdf
 
- id: doi:10.1021/acs.jpclett.0c00335
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpclcd/2020/jpclcd.2020.11.issue-7/acs.jpclett.0c00335/20200327/images/large/jz0c00335_0006.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpclett.0c00335.pdf

- id: doi:10.1021/acscatal.9b05544
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/accacs/2020/accacs.2020.10.issue-6/acscatal.9b05544/20200316/images/large/cs9b05544_0011.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acscatal.9b05544.pdf
      
- id: doi:10.1002/prot.25885
  image: https://onlinelibrary.wiley.com/cms/asset/b6fbc343-8371-4cf5-b29c-05663cfb0f7c/prot25885-fig-0001-m.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/prot.25885.pdf
 
- id: doi:10.1021/acs.jpcc.9b07860
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2019/jpccck.2019.123.issue-50/acs.jpcc.9b07860/20191212/images/medium/jp9b07860_0005.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.9b07860.pdf
 
- id: doi:10.1021/acs.nanolett.9b03056
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/nalefd/2019/nalefd.2019.19.issue-10/acs.nanolett.9b03056/20191003/images/large/nl9b03056_0009.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.nanolett.9b03056.pdf
 
- id: doi:10.1103/PhysRevApplied.12.024044
  image: https://journals.aps.org/prapplied/article/10.1103/PhysRevApplied.12.024044/figures/2/medium
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/PhysRevApplied.12.024044.pdf
 
- id: doi:10.1021/acs.jpcc.9b03418
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2019/jpccck.2019.123.issue-36/acs.jpcc.9b03418/20190905/images/large/jp-2019-03418f_0005.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.9b03418.pdf
 
- id: doi:10.1021/acsami.9b06010
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aamick/2019/aamick.2019.11.issue-22/acsami.9b06010/20190529/images/medium/am-2019-06010u_0007.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acsami.9b06010.pdf
 
- id: doi:10.1021/acs.jpcb.8b10980
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpcbfk/2019/jpcbfk.2019.123.issue-18/acs.jpcb.8b10980/20190506/images/medium/jp-2018-10980a_0012.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcb.8b10980.pdf
 
- id: doi:10.1021/acs.jpcc.8b09868
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2018/jpccck.2018.122.issue-51/acs.jpcc.8b09868/20181220/images/medium/jp-2018-09868k_0010.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.8b09868.pdf
 
- id: doi:10.1103/PhysRevLett.121.056601
  image: https://journals.aps.org/prl/article/10.1103/PhysRevLett.121.056601/figures/3/medium
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/PhysRevLett.121.056601.pdf
 
- id: doi:10.1021/acs.jpcc.8b03743
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2018/jpccck.2018.122.issue-28/acs.jpcc.8b03743/20180712/images/large/jp-2018-03743r_0005.jpeg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.8b03743.pdf
 
- id: doi:10.1021/acsami.8b05864
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/aamick/2018/aamick.2018.10.issue-24/acsami.8b05864/20180614/images/medium/am-2018-05864p_0004.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acsami.8b05864.pdf
 
- id: doi:10.1149/2.1251805jes
  image: https://cfn-live-content-bucket-iop-org.s3.amazonaws.com/journals/1945-7111/165/5/A1099/revision1/A1099fig1.jpeg?AWSAccessKeyId=AKIAYDKQL6LTV7YY2HIK&Expires=1676500747&Signature=VggG0ZGxmZK2UnF5ZQOJFH0I2wQ% https://cfn-live-content-bucket-iop-org.s3.amazonaws.com/journals/1945-7111/165/5/A1099/revision1/A1099fig1.jpeg?AWSAccessKeyId=AKIAYDKQL6LTV7YY2HIK&Expires=1676500747&Signature=VggG0ZGxmZK2UnF5ZQOJFH0I2wQ%3D3D 
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/2.1251805jes.pdf
 
- id: doi:10.1021/acscatal.7b04347
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/accacs/2018/accacs.2018.8.issue-5/acscatal.7b04347/20180430/images/medium/cs-2017-04347y_0009.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acscatal.7b04347.pdf
 
- id: doi:10.1021/acs.nanolett.7b04444
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/nalefd/2018/nalefd.2018.18.issue-1/acs.nanolett.7b04444/20180109/images/medium/nl-2017-044449_0006.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.nanolett.7b04444.pdf
 
- id: doi:10.1016/j.jpowsour.2017.10.050
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0378775317313939-fx1.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/j.jpowsour.2017.10.050.pdf
 
- id: doi:10.1039/C7CP02350B
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C7CP02350B&imageInfo.ImageIdentifier.Year=2017
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/c7cp02350b.pdf
 
- id: doi:10.1021/acs.jpcc.7b02777
  image: https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/jpccck/2017/jpccck.2017.121.issue-19/acs.jpcc.7b02777/20170512/images/medium/jp-2017-02777e_0009.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/acs.jpcc.7b02777.pdf
 
- id: doi:10.1103/PhysRevB.95.035301
  image: https://journals.aps.org/prb/article/10.1103/PhysRevB.95.035301/figures/1/medium
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/PhysRevB.95.035301.pdf
 
- id: doi:10.1016/j.corsci.2016.10.001
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0010938X16309179-gr1.jpg
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/j.corsci.2016.10.001.pdf
 
- id: doi:10.1063/1.4962748
  image: https://aip.scitation.org/na101/home/literatum/publisher/aip/journals/content/jcp/2016/jcp.2016.145.issue-11/1.4962748/production/images/medium/1.4962748.figures.f2.gif
  extra-links:
    - type: pdf
      link: https://valexandrov.github.io/webpage/papers/1.4962748.pdf
